# Generated by Django 5.1.1 on 2024-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='product_catagory',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('s', 's'), ('L', 'L'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=100),
        ),
    ]
